# Generated by Django 3.1.4 on 2021-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseComponent', models.CharField(max_length=50)),
                ('courseOutcomes', models.CharField(max_length=50)),
                ('courseWeight', models.CharField(max_length=10)),
            ],
        ),
    ]
