# Generated by Django 3.1.4 on 2021-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPAConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNum', models.CharField(max_length=10)),
                ('letterGrade', models.CharField(max_length=10)),
                ('totalMark', models.IntegerField()),
            ],
        ),
    ]
